# Made by Magnus Anderson for a bigger neofetch
logo = [
    "                        ;,                        ",
    "                        %i                        ",
    "                       =vI=                       ",
    "                      .IIII.                      ",
    "                      )IIIIi                      ",
    "                     :IIIIII;                     ",
    "                     vIIIIIII.                    ",
    "                    )llIIIIIIi                    ",
    "                   .IlvlvlIIII;                   ",
    "                    =llIIIIIIvl,                  ",
    "                  =. -<IIIIIIIIi.                 ",
    "                 =vi>_.=iIIIIIIv(                 ",
    "                .vIIIii_:+lvlvlIl;                ",
    "               .%vlIIIIII|%IIIIIII,               ",
    "               )lIIIIIIIIvIIIIIIIIi.              ",
    "              =vlIIIIIIIIIIIIIIIIIv(              ",
    "             _vlIIIIIIIIIIIIIIIIIIIl=             ",
    "            .vlIIIIIIIIIIIIIIIIIIIIIv,            ",
    "            %lIIIIIIIII%+|iIIIIIIIIIIl.           ",
    "           )IIIIIIIII%`    -{IIIIIIIIIi           ",
    "          =vlIIIIIII%`       {vlvlvlIII(          ",
    "         _vlIIIIIIII'        -vlIIlIvlII;         ",
    "        .vlIIIIIIIIl          <vI|+|iIIII,        ",
    '        vllvlIIIIII>          <lIi=_:.<"il.       ',
    "       )llIIIIIIIII>          =lvIvvi|=.. -       ",
    "      <lIvlIIIIIIIv>          =vlIIlllIi|=.       ",
    "     _vlIIIIIIIIIl|+          =|lIIIIvlvIIi;      ",
    '    .vvlIIIIIi"~-                --"iIIlIIIvi,    ',
    "   .vIlIIl+~                          ~+lvlIIl.   ",
    "   %lIl+`                                -+lvIi   ",
    "  )I+~                                      -+v(  ",
    " :~                                            ~: ",
]
